name: Deploy to ECR
# updated secrets
on: 
  push:
    branches: [ master ]

jobs:
  
  build:
    
    name: Build Image
    runs-on: ubuntu-latest

   
    steps:

    - name: Check out code
      uses: actions/checkout@v3

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      env:
        AWS_ACCESS_KEY_ID: ${{ ASIA6CNBUANSI4IQZ6TL }}
        AWS_SECRET_ACCESS_KEY: ${{ BYo2bLVchQFFzETVqBn3gHSke1r6u1dD6uPD45B9 }}
        AWS_SESSION_TOKEN: ${{ FwoGZXIvYXdzECcaDDAOPLpXA77Q/M+KQyLFAaG9Qd3k4GyhpRYb1cpMd/1azlE17xJ6euhpP00D+aZJgk4gxUMt7USwKTYO36MjK39+6zlxPfLNAc01xLVL3v+bkhFf0/M3IbMClwPnk9KxqjRXn6Y0EmN8U7e9jzbBuipeYbOi9IriZbNjWBe2iMqK4N9iwlOKUHXUFG3nyGm5D0DcW3q0nxatU4M78fNvJrvxIr5dwZ7yNQHsRNJqSntvsRhB/fDNT90ZcOzWjjTU7DXgtp+wIlOc+zWk0dEZQ4SOf2sLKJvsyaMGMi2B248J41ntOsI293oU9cBNX+/2Q0sMEs5xokHgkecKaIClfBSflfJNillyMzA= }}
        AWS_REGION: us-east-1

    - name: Build, test, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: clo835-week3-1
        IMAGE_TAG: v0.1
      run: |
        cd Chapter02/kubia/
        ls -ltra
        # Docker build command
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        # Unit test
        docker run -d -p 80:8080 --name nodeapp $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        docker ps
        echo "Pause for 10 seconds to let container start"
        sleep 10
        curl localhost -vvv
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
